import { ArrowRight, FileText, LockKeyhole, MessageSquareText, ScanSearch, ShieldCheck } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useAnalyzeMessage } from '@workspace/api-client-react';
import { AnalysisResultView } from '@/components/analysis-result';
import { EmptyState, PageHeader, QueryError, SkeletonBlock } from '@/components/ui-kit';

export default function MessageAnalyzer() {
  const [message, setMessage] = useState('');
  const analyze = useAnalyzeMessage();
  const submit = (event: FormEvent) => { event.preventDefault(); if (message.trim().length >= 10) analyze.mutate({ data: { message: message.trim() } }); };
  return <div className="cg-page mx-auto max-w-[1120px]"><PageHeader eyebrow="Analysis lab · message" title="Read the pressure behind the words." description="Paste an email, SMS, or direct message. We will surface urgency, impersonation, payment pressure, and other fraud signals." />
    <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><section className="cg-panel p-5 md:p-7"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent/18 text-[hsl(28_81%_44%)]"><MessageSquareText size={21} /></div><h2 className="mt-5 text-[19px] font-extrabold tracking-[-.04em]">Message risk review</h2><p className="cg-prose mt-2">Keep the text intact for a stronger read. Remove private details if you do not want them analyzed.</p><form onSubmit={submit} className="mt-6 space-y-3"><div className="flex items-center justify-between"><label htmlFor="message-input" className="cg-kicker">Message text</label><span data-testid="text-message-character-count" className="cg-mono text-[10px] text-muted-foreground">{message.length} chars</span></div><textarea id="message-input" data-testid="input-message-analysis" value={message} onChange={(event) => setMessage(event.target.value)} className="cg-input min-h-[190px] resize-y leading-relaxed" placeholder="Paste the message you want to inspect…" /><button data-testid="button-submit-message-analysis" disabled={analyze.isPending || message.trim().length < 10} className="cg-btn cg-btn-primary w-full disabled:cursor-not-allowed disabled:opacity-50">{analyze.isPending ? <><ScanSearch size={14} className="animate-pulse" />Reading signal…</> : <>Analyze message <ArrowRight size={14} /></>}</button>{analyze.isError && <div className="rounded-lg border border-destructive/20 bg-destructive/8 p-3 text-[11px] text-destructive">We could not analyze this message. Try again in a moment.</div>}</form><div className="mt-7 grid gap-3 border-t border-border pt-5 sm:grid-cols-2"><div className="rounded-lg bg-muted/60 p-3"><FileText size={14} className="mb-2 text-primary" /><div className="text-[11px] font-bold">More context helps</div><div className="mt-1 text-[10px] leading-relaxed text-muted-foreground">Keep the sender, ask, and call to action.</div></div><div className="rounded-lg bg-muted/60 p-3"><LockKeyhole size={14} className="mb-2 text-primary" /><div className="text-[11px] font-bold">Defensive by design</div><div className="mt-1 text-[10px] leading-relaxed text-muted-foreground">Your text is used for this analysis only.</div></div></div></section><section className="min-h-[550px]">{analyze.isPending ? <div className="cg-panel space-y-4 p-6"><SkeletonBlock className="h-14 w-48" /><SkeletonBlock className="h-24" /><SkeletonBlock className="h-24" /><SkeletonBlock className="h-40" /></div> : analyze.data ? <AnalysisResultView result={analyze.data} /> : analyze.isError ? <QueryError label="Analysis service unavailable." /> : <div className="cg-panel h-full"><EmptyState icon={ShieldCheck} title="No message in review" detail="Paste a message to reveal its risk signals and get a clear recommendation." /></div>}</section></div>
  </div>;
}