import { ArrowRight, Globe2, Link2, ScanSearch, ShieldCheck } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useAnalyzeUrl } from '@workspace/api-client-react';
import { AnalysisResultView } from '@/components/analysis-result';
import { EmptyState, PageHeader, QueryError, SkeletonBlock } from '@/components/ui-kit';

export default function UrlAnalyzer() {
  const [url, setUrl] = useState('');
  const analyze = useAnalyzeUrl();
  const submit = (event: FormEvent) => { event.preventDefault(); if (url.trim().length >= 3) analyze.mutate({ data: { url: url.trim() } }); };
  return <div className="cg-page mx-auto max-w-[1120px]"><PageHeader eyebrow="Analysis lab · URL" title="Check before you click." description="Paste a link and CyberGuard will unpack the signals behind its risk posture — without visiting it in your browser." />
    <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><section className="cg-panel cg-grid-bg p-5 md:p-7"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/12 text-primary"><Globe2 size={21} /></div><h2 className="mt-5 text-[19px] font-extrabold tracking-[-.04em]">URL reputation check</h2><p className="cg-prose mt-2">We look for impersonation, suspicious redirects, domain age patterns, and other defensive indicators.</p><form onSubmit={submit} className="mt-6 space-y-3"><label htmlFor="url-input" className="cg-kicker block">URL to inspect</label><div className="relative"><Link2 className="absolute left-3 top-3.5 text-muted-foreground" size={16} /><input id="url-input" data-testid="input-url-analysis" value={url} onChange={(event) => setUrl(event.target.value)} className="cg-input pl-10" placeholder="https://example.com/login" type="url" /></div><button data-testid="button-submit-url-analysis" disabled={analyze.isPending || url.trim().length < 3} className="cg-btn cg-btn-primary w-full disabled:cursor-not-allowed disabled:opacity-50">{analyze.isPending ? <><ScanSearch size={14} className="animate-pulse" />Inspecting signals…</> : <>Analyze URL <ArrowRight size={14} /></>}</button>{analyze.isError && <div className="rounded-lg border border-destructive/20 bg-destructive/8 p-3 text-[11px] text-destructive">We could not analyze that URL. Check the address and try again.</div>}</form><div className="mt-7 border-t border-border pt-5"><div className="cg-kicker mb-3">Good to know</div><div className="space-y-3"><div className="flex gap-2 text-[11px] text-muted-foreground"><ShieldCheck size={14} className="shrink-0 text-primary" />No page content is loaded in your browser.</div><div className="flex gap-2 text-[11px] text-muted-foreground"><ShieldCheck size={14} className="shrink-0 text-primary" />Results explain the evidence, not just a label.</div></div></div></section><section className="min-h-[490px]">{analyze.isPending ? <div className="cg-panel space-y-4 p-6"><SkeletonBlock className="h-14 w-48" /><SkeletonBlock className="h-24" /><SkeletonBlock className="h-24" /><SkeletonBlock className="h-40" /></div> : analyze.data ? <AnalysisResultView result={analyze.data} /> : analyze.isError ? <QueryError label="Analysis service unavailable." /> : <div className="cg-panel h-full"><EmptyState icon={ScanSearch} title="Your result will land here" detail="Enter a URL to see its classification, confidence, evidence, and recommended next step." /></div>}</section></div>
  </div>;
}